[project]
authors = [
    {name = "Spyros Roum", email = "spyros.roum@posteo.net"},
]
requires-python = ">=3.11"
name = "eyes"
version = "0.1.0"
description = ""
readme = "README.md"

dependencies = [
    "litestar<3.0.0,>=2.14.0",
    "uvicorn[standard]<1.0.0,>=0.34.0",
]
